language: cpp
sudo: required
dist: trusty
compiler: gcc
os: linux

before_install:
  - export DEBIAN_FRONTEND=noninteractive
  - sudo -E apt-get -yq update &>> ~/apt-get-update.log
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libgtkmm-3.0-dev libsdl2-dev 
script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" ..
  - make
